/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_video_codec_OpenH264Codec */

#ifndef _Included_com_zayhu_video_codec_ads
#define _Included_com_zayhu_video_codec_ads
#ifdef __cplusplus
extern "C" {
#endif
//触发一帧
/*JNIEXPORT jint JNICALL Java_com_zayhu_video_player_MediaWaterMark_nativeTirgger
 (JNIEnv *env, jobject obj, jlong context,
 jbyteArray h264buffer,jint h264bufferlen
 );*/
 JNIEXPORT jint JNICALL Java_com_zayhu_video_player_MediaWaterMark_nativeTirgger
  ( jlong context,
  jbyteArray h264buffer,jint h264bufferlen
  );
#ifdef __cplusplus
}
#endif
#endif
